stages:
    - validate
    - test

style_check:
  stage: validate
  image: sensirion/embedded-ci:2.2.0
  tags: [linux, docker]
  script:
    - clang-format -i src/* --style=file
    - git diff --exit-code

# Note: lint check will only pass once the library is published on the
#       Arduino library manager (https://github.com/arduino/library-registry)

# lint_check:
#   stage: validate
#   image: sensirion/embedded-ci:2.2.0
#   tags: [linux, docker]
#   script:
#     - cd /usr/local
#     - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-lint/main/etc/install.sh | sh
#     - arduino-lint /builds/MSO-SW/unified-prototyping-toolkit/upt-core --library-manager update

cpp_check:
    stage: validate
    image:
        name: registry.gitlab.sensirion.lokal/mso-sw/drivers/docker-driver-generator:0.1.0
    tags: [linux, docker]
    script:
        - cppcheck --std=c++11 --language=c++ --error-exitcode=1 --enable=warning,performance,portability src/*

compile_test:
    stage: test
    image:
        name: registry.gitlab.sensirion.lokal/sensirion/docker/docker-arduino:0.5.0
    tags: [docker, linux]
    needs: []
    script:
        - arduino-cli update
        - mkdir -p /root/Arduino/libraries/
        - ln -s $PWD ~/Arduino/libraries/
        - arduino-cli compile --warnings all --fqbn esp32:esp32:esp32 examples/BasicUsage
