name: Arduino Lib

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    Arduino-Checks:
        uses: sensirion/.github/.github/workflows/upt.arduino.check.yml@main
        with:
            expect-arduino-examples: true
            lint-lib-manager-check: update
