name: PIO Lib

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"

jobs:
    PlatformIO-Check:
        uses: ./.github/workflows/platformio_check_template.yml
        with:
            pio-environment-list: '["ble_example", "basicUsage"]'

    PlatformIO-Build:
        uses: ./.github/workflows/platformio_build_template.yml
        needs: PlatformIO-Check
        with:
            pio-environment-list: '["ble_example", "basicUsage"]'

    PlatformIO-Package:
        if: ${{ (github.ref_type != 'tag') && (github.ref_name == 'master') }}
        needs: PlatformIO-Build
        uses: ./.github/workflows/platformio_publish_template.yml
        with:
            should-publish: false

    PlatformIO-Publish:
        uses: ./.github/workflows/platformio_publish_template.yml
        if: ${{ (github.ref_type == 'tag') && (github.ref_name == 'master') }}
        needs: PlatformIO-Build
        with:
            should-publish: true
        secrets:
            pio-registry-token: ${{ secrets.PIO_MKTSW_TOKEN }}
